### PR TITLE
Prosthetic Chassis Repair + Prosthetic Electronic Repair

### PR DESCRIPTION
**Pull request by BootlegBow**
## About The Pull Request

This adds two new surgeries for repairing cybernetic limbs.
Same steps as Prosthesis Organ Manip, but with welder/cable instead of a hemostat.
Self-operable so you can still repair yourself, and doesn't need you to lie down.
Also removes the old basic welder/cable repair

Whilst coding this I found out that suiciding with a welder displays "welds every orifice closed"
nightmare fuel yaaaaaaay

## Why It's Good For The Game

Slapping your arm with a welder to fix it is boring, and if all your limbs are cybernetic a tad busted since you could heal heaps of brute in a short period of time

## Changelog
:cl:
add: prosthetic chassis repair and prosthetic electronic repair surgeries
del: you can no longer heal prosthetic limbs with just a welder/cable
/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
how the fuck did you mess this up

**Comment by BootlegBow** [comment]
it compiled locally what the fuck

**Comment by JohnFulpWillard** [comment]
>  del: you can no longer heal prosthetic limbs with just a welder/cable

How are they meant to heal outside of surgeries?

**Comment by Kitsunemitsu** [comment]
I recommend that you allow both.

**Comment by BootlegBow** [comment]
i'd like to remove the 25 damage cap and make surgery only required if damage on the limb exceeds 25, but i'm not quite sure to do that
i'll draft the pr for now until i can figure that out

**Comment by BootlegBow** [comment]
now that i think of it this is a fucking stupid idea

**Pull request closed without merging**
