### PR TITLE
The Pistol PR

### PR DESCRIPTION
**Pull request by retlaw34**
## About The Pull Request
This does... Quite a bit
Adds a new variant of the makarov, works the same except its clearly not syndicate
Adds the terragov guns except the rifle, sprites made by @Kitsunemitsu 
adds the colt elite delta, changes the mag to 9mm and makes it unorderable from cargo
fixes the XO2 SIZE FINALLY

## Why It's Good For The Game

Increases bloat and unused items

## Changelog
:cl:
add: guns
fix: the XO2 should now fit in a bag
/:cl:

### CODE REVIEW

**Comment by retlaw34** [comment]
nah

**Comment by Kitsunemitsu** [comment]
Netta you bastard I didn't give you these sprites for nothing

**Comment by retlaw34** [comment]
finneee

**Comment by Kitsunemitsu** [comment]
I added them into marine corps.

**Comment by retlaw34** [comment]
Oh

**Pull request closed without merging**
