### PR TITLE
Ports TG's nitrile glove buffs

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Porting over Nitrile glove buffs, which includes the removal of the quickcarry skillchip.

## Why It's Good For The Game

Better for medical

## Changelog
:cl:
balance: Nitrile gloves now let you fireman carry people quicker and allow medical applications faster.
/:cl:

### CODE REVIEW

**Comment by EgorDinamit** [comment]
Hello? #113

**Comment by JohnFulpWillard** [comment]
> 
> 
> Hello? #113

Didnt notice it, was just reading the code and thought they might want it.

**Comment by EgorDinamit** [comment]
Oh, fair enough. Why did you leave the Discord anyway?

**Comment by JohnFulpWillard** [comment]
> 
> 
> Oh, fair enough. Why did you leave the Discord anyway?

I only joined to find the Github

**Pull request closed without merging**
