### PR TITLE
Cloning fix/tweak

### PR DESCRIPTION
**Pull request by EgorDinamit**
Ports:
vlggms/tegustation/pull/146
vlggms/tegustation/pull/151

## About The Pull Request

Re-adds experimental cloning code and makes it work properly.
Fixes some issues about cloning in general.

## Why It's Good For The Game

Cloning still has a bunch of issues, so we will work on fixing them.
And as I always say - bugs = bad.

### CODE REVIEW

**Comment by BootlegBow** [comment]
will need testmerging to make sure it works with our cloning

**Comment by EgorDinamit** [comment]
> will need testmerging to make sure it works with our cloning

Your cloning is literally the same, so it should work just fine.

**Comment by BootlegBow** [comment]
> > will need testmerging to make sure it works with our cloning
> 
> Your cloning is literally the same, so it should work just fine.

technically it isn't since we have clone imperfections and this looks like it touches brain traumas related to cloning

**Comment by Kitsunemitsu** [comment]
Looks about good to go

**Pull request merged**
