### PR TITLE
LUFR ruin tweaks

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

LUFR spawner now doesn't turn you into an ashwalker lizard.
Atmos in the ruin itself is now breathable and there are some oxygen tanks around.

## Why It's Good For The Game

Doesn't make too much sense lorewise and... otherwise.
This spawner is meant to be a semi-hostile hermit if anything and I believe they should be able to use guns/kinetic accelerators if they have to.

### CODE REVIEW

**Comment by thevandie** [comment]
is there a minifan at the door?

**Comment by Kitsunemitsu** [comment]
Map changes from the person who made the map.
Merging.

**Comment by EgorDinamit** [comment]
> is there a minifan at the door?

Yes.

**Comment by Kitsunemitsu** [comment]
give me an @ when you want me to merge this, it's all you

**Pull request merged**
