### PR TITLE
LGBT Socks

### PR DESCRIPTION
**Pull request by retlaw34**
## About The Pull Request
image
image
Adds the LGBT socks by @tiramisuapimancer
Ports https://github.com/shiptest-ss13/Shiptest/pull/8/

## Why It's Good For The Game
image

A side effect of this is that it's a surprisingly good way of sifting out shitters.

## Changelog
:cl:
add: Bunch of new socks
tweak: Ethereals can wear underclothes
/:cl:

### CODE REVIEW

**Comment by HighPrincessErinys** [comment]
retlaw you fool!! you idiot!! i just gave you the idea!! tira sprited these!!

**Comment by retlaw34** [comment]
A

**Comment by retlaw34** [comment]
Fixed the description

**Review by BootlegBow — APPROVED** [review]
watch me merge before the checks complete

**Comment by HighPrincessErinys** [comment]
while we're here, play shi-

**Comment by triplezeta** [comment]
image

**Comment by HighPrincessErinys** [comment]
> while we're here, play shi-

-ptest

**Comment by BootlegBow** [comment]
i've scared off the shiptesters with my speed and agility

**Pull request merged**
