### PR TITLE
Solgov Representative

### PR DESCRIPTION
**Pull request by retlaw34**
## About The Pull Request

New job: Solgov Representative
I know the original plan was for terragov, but since i got permission to use these sprites + they look way better, I decided why not. Sorry Egor, if you are still listening.

This is more of a RP role than any mechanical use, however...
They get access to the solgov radio, to ask solgov (admins) for things.
They get another letter opener to duel the sercetary

Only enabled on packed, disabled on every other map

This also includes a fix to make bungalow compile on 514, although theres still other errors when running the server on 514.
Heavy WIP
sprites by @triplezeta

## Why It's Good For The Game

"they facilitate communication between various departments and act as a mediator, and occasionally can act as a field medic if one of the SGRs is out in the field and the actual medic gets incapacitated"

I also wanted these for galaxy
## Changelog
:cl:
add: Solgov stuff
add: Solgov Representative, a new 'head' and more of a RP role than anything.
imageadd: Some terragov things were replaced by solgov
fix: Bungalow now compiles on 514
/:cl:

### CODE REVIEW

**Comment by EgorDinamit** [comment]
TerraGov Representative..........

**Comment by BootlegBow** [comment]
Secretary 2, political diplomat edition

**Comment by retlaw34** [comment]
how many conflicts does this have

**Comment by retlaw34** [comment]
none apparently

**Comment by retlaw34** [comment]
OH

**Comment by thevandie** [comment]
I mean, tbf SG makes more sense for a frontier research station.

**Comment by retlaw34** [comment]
Better yet, let me kill modularTegustation first then reopen it

**Comment by triplezeta** [comment]
why :(

**Comment by triplezeta** [comment]
why closed,

**Pull request closed without merging**
