### PR TITLE
Increases our server to HRP

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request

Our server is now HRP. The LRP race of "Human" is no longer selectable.

## Why It's Good For The Game

More RP, Less LRP behaviour

## Changelog
:cl:
del: Removed humans
tweak: tweaked our server to HRP
/:cl:

### CODE REVIEW

**Comment by retlaw34** [comment]
now the real hrp thing to do is disable all races besides felinds

**Comment by HugoOdaX** [comment]
:trollface:

**Comment by Kitsunemitsu** [comment]
Greytide Stationwide

**Comment by BootlegBow** [comment]
fun fact
you can testmerge closed prs

**Pull request closed without merging**
