### PR TITLE
Security Titles

### PR DESCRIPTION
**Pull request by thevandie**
## About The Pull Request

Adds and changes a bunch of different security titles to fit better with the lore (that I just created). (Also, hopefully the senior titles don't break. I added a list behind a few of them to get the extra names in).

## Why It's Good For The Game

Tons of variety for the different roles is always a nice thing, especially if you want to express yourself more in your role. Also, Commander (navy) is in there for lore reasons.

## Changelog
:cl:
add: "Sergeant Officer" and "Intelligence Officer" as security titles.
tweak: Replaces "Sergeant" with "Security Sergeant", "Sergeant Major" with "Man-At-Arms" - "Security Major", and "Staff Sergeant" with "Chief Investigator"
/:cl:

### CODE REVIEW

**Comment by thevandie** [comment]
I tested it in-game and so far as I can tell it does indeed work. Commander and security sergeant show up. Not sure about the senior titles as I can't really test those right now, but I assume they do work as well.

**Comment by Kitsunemitsu** [comment]
Adding commander to the Alt Job titles when we already have a Solgov commander will cause issues. I don't recommend doing this.
Not only that, but Captain Jobs tend to have a unique outfit and ID. 
I can assist you with those but it's probably out of the scope of this PR.

**Comment by thevandie** [comment]
on it now

**Comment by thevandie** [comment]
Removed commander. should be good now

**Comment by Kitsunemitsu** [comment]
Looks Great, merging!

**Pull request merged**
