### PR TITLE
fixes HFR corner

### PR DESCRIPTION
**Pull request by 1393F**
## About The Pull Request
this readds the HFR corner sprite

## Why It's Good For The Game
I like being able to use the HFR

## Changelog
:cl:
fix: HFR corners have sprites again
/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
This is an Issue with a PR we have test merged, and Jones is supposed to fix it.

**Comment by 1393F** [comment]
should i just close this then?

**Comment by Kitsunemitsu** [comment]
Yeah, we have to wait for jones to fix it

**Comment by BootlegBow** [comment]
woulda been nice if you bloody told me @Kitsunemitsu

**Pull request closed without merging**
