### PR TITLE
nerfs chaos marine's chainsword and replaces bubble's spellblade for ninja shoes

### PR DESCRIPTION
**Pull request by 1393F**
I'm bad at explaining things
## About The Pull Request
chaos marine's chainsword damage has been lowered from 30 to 15
armor penetration lowered from 50 to 30
block chance removed

fireball wand from ashdrake loot removed

bubble's spellblade replaced with ninja shoes(no-slip+-1 speed slowdown)
(I couldn't think of anything better to give both in rarity and usability) 

## Why It's Good For The Game
miner weapons that more or less is only given to kill crew with is bad?

### CODE REVIEW

**Comment by thevandie** [comment]
I like this. ngl, screw power gamers.

**Comment by retlaw34** [comment]
i think chainblade should be at a bit more since it is loot, otherwise everything else looks okay
mining is just a clusterfuck in general, to be honest

**Comment by 1393F** [comment]
> i think chainblade should be at a bit more since it is loot

I disagree, the current chainsword may as well be a fireaxe that you can store in the belt slot. Megafauna loot(in my opinion) should be about defense(armor) and usability(actually being able to use what you get) and NOT about getting weapons(mostly). The new stats make it a better version of the cleaving saw

**Comment by thevandie** [comment]
I mean, if possible the best-case scenario would be to only have it be OP outside of the station Z level and then have it be nerfed on-station.

**Comment by retlaw34** [comment]
> 
> 
> > i think chainblade should be at a bit more since it is loot
> 
> I disagree, the current chainsword may as well be a fireaxe that fits in the belt slot. Megafauna loot(in my opinion) should be about defense(armor) and usability(actually being able to use what you get) and NOT about getting weapons solely meant to kill crew with. The new stats make it a better version of the cleaving saw

Yeah, I agree with that

**Review by retlaw34 — APPROVED** [review]

**Comment by Kitsunemitsu** [comment]
PR by the miner coder with approval from a dev. Merging.

**Pull request merged**
