### PR TITLE
John willard's a failure, can't have shit in Detroit.

### PR DESCRIPTION
**Pull request by FernandoJ8**
## About The Pull Request

HEEHEE WOW LOOK AT ME I'M A FULPSTATION CODER, OH LOOK AT MY BEAUTIFUL "MODULAR" CODE THATS ONLY MODULAR WHEN THE FUCKING HEADCODER ENFORCES IT! MY CODE IS SO FUCKING ABSOLUTELY MODULAR FROM OVERWRITING AN ESSENTIAL TG FUNCTION, JUST BECAUSE IT DOESN'T EDIT A TG FILE THAT WAY! YEP! NO COMPLAINTS FROM THE HEADCODER! NO COMPLAINTS FROM A FELLOW CODER! I WAS JUST CODING AND OVERWROTE AN ENTIRE FUNCTION FOR MY STUPID FUCKING FEATURE! EDITING TG FILES? SOUNDS LIKE YOU'RE JUST A FUCKING SHITCODER. PARDON MY INNABILITY TO FUCKING TALK PERRPEDRLY AS I FUCKING BREAK THE ENTIRE GAME BY A SINGLE OVERWRITE, RESULTING IN THOUSANDS (AND YES, AGGONNIZZINGG FUCKING) RUNTIMES, CRASHING THE SERVER!
Honestly fulp coders are so fucking stupid. nobody who actually codes tries to modularize it. Its an inbetween semi-modular/non-modular at most. And when people ARE ACTUALLY having working features, they do it by editing TG files. half of the fulp coders are okay while the other half are completely fucking real life brain damaged. Honestly, why the FUCK would you MODULARIZE something that WILL BREAK no matter what? WHAT FUCKING REASON do you have to tell me to modularize my code for something that NOBODY other than your stupid, fucking horrible programming self had a problem with. I hate Baycode, and I think that most of t heir coders aren't the best (same for TG) but you know what they do right? They let people code without restraints. As long as something is a good feature, as long as maintainers aren't complaining, they let it be. OH, AND TO FUCKING TOP IT ALL OFF, AND THIS, THIS IS FUCKING UNFORGIVABLE, ON THE REPOSITORY'S PAGE, THE FUCKING LINK THAT IS FOR "DISCORD" DOESN'T EVEN REDIRECT TO A FULP CODERBUS. WHAT DO YOU WANT ME TO DO? JOIN YOUR SHITTY FUCKING DISCORD SERVER? Fuck fulp coders. fucking shitty ass coders.

## Why It's Good For The Game

John's a failure and didn't even include me. Sloppy work. Where's the lamb sauce.

## Changelog
:cl:
del: Deletes minors, for real this time.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
I was planning an update that adds more people

**Comment by FernandoJ8** [comment]
> 
> 
> I was planning an update that adds more people

images

**Comment by BootlegBow** [comment]
are we just gonna keep adding to this list over time

**Comment by FernandoJ8** [comment]
> 
> 
> are we just gonna keep adding to this list over time

**Comment by BootlegBow** [comment]
holy fuck why is that png so big

**Comment by Kitsunemitsu** [comment]
Sorry I rushed to my PC to speedmerge so that John Willard's (this guy keeps following me for some reason) mistakes can be shown off to the world

**Comment by FernandoJ8** [comment]
> 
> 
> holy fuck why is that png so big

643b5e7e06e66313549b7209faba9a19

**Comment by Kitsunemitsu** [comment]
I am requesting reviews from some reviewers because that it what I would do if I was coded for the upstream (TGstation, objectively the best station) and not wasting my time coding for fun and dealing with bullshit.

**Comment by FernandoJ8** [comment]
> 
> 
> Sorry I rushed to my PC to speedmerge so that John Willard's (this guy keeps following me for some reason) mistakes can be shown off to the world

6026ee86cd3c7

**Comment by FernandoJ8** [comment]
I'm answering to all replies using the first result that comes in google when I look up "[reply] + 'meme' "

**Comment by BootlegBow** [comment]
these pngs are wider than your mum

**Comment by JohnFulpWillard** [comment]
> 
> 
> I am requesting reviews from some reviewers because that it what I would do if I was coded for the upstream (TGstation, objectively the best station) and not wasting my time coding for fun and dealing with bullshit.

What about your upstream TheSwain/Fulpstation?

**Comment by EgorDinamit** [comment]
> > I am requesting reviews from some reviewers because that it what I would do if I was coded for the upstream (TGstation, objectively the best station) and not wasting my time coding for fun and dealing with bullshit.
> 
> What about your upstream TheSwain/Fulpstation?

Their upstream is not Fulpstation, kid.

**Pull request merged**
