### PR TITLE
Keeps kids out of the game

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

image

## Why It's Good For The Game

They've spoken

## Changelog
:cl:
del: Underage people
/:cl:

### CODE REVIEW

**Review by SgtHunk — APPROVED** [review]

**Review by Kitsunemitsu — APPROVED** [review]
Looks pretty good!

**Comment by Kitsunemitsu** [comment]
Just waiting for another reviewer

**Comment by BootlegBow** [comment]
based

**Review by BootlegBow — APPROVED** [review]

**Comment by Kitsunemitsu** [comment]
It's been merged! Welcome to our contributor list

**Comment by BootlegBow** [comment]
he was already on the list kirie

**Comment by Kitsunemitsu** [comment]
Well, you know

**Comment by XanHiroki** [comment]
Very cool Kirie thank you.

**Pull request merged**
