### PR TITLE
You can stand in sofcrit, but not for long before colapsing if you take more damage

### PR DESCRIPTION
**Pull request by retlaw34**
## About The Pull Request

A very basic implmentation of no knockdown on crit

This has been updated, you will still stand on crit but at a certain thresholdd you will fall down (old softcrit behavior) and then go into hardcrit as usual

This is mostly here to show its possible

## Why It's Good For The Game

less frustrating deaths i guess

## Changelog
:cl:
tweak: Being in crit should no longer knock you down
/:cl:

### CODE REVIEW

**Comment by XanHiroki** [comment]
no more horizontal death sentences, only standing ones.

**Comment by BootlegBow** [comment]
i shall die standing

**Comment by EgorDinamit** [comment]
This kills the balance and makes luxury survival pens obsolete.

**Comment by retlaw34** [comment]
Yeah id rather work on mapping stuff rather than a rework this big, maybe ill pick it up later

**Comment by Kitsunemitsu** [comment]
I'm taking control of this PR.

**Comment by Kitsunemitsu** [comment]
People seem to like this, I will be asking the discord and then possibly merging

**Pull request merged**
