### PR TITLE
[PORT] Balloon Alerts

### PR DESCRIPTION
**Pull request by 1393F**
## About The Pull Request
https://github.com/tgstation/tgstation/pull/59130
https://github.com/tgstation/tgstation/pull/59256

## Why It's Good For The Game
looks nice

## Changelog
:cl:
qol: Changing a reagent container's transfer amount will now give you feedback in the form of text on the container itself.
/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
Ok, we can have this, but I'd like the chat message for logging purposes

**Comment by Kitsunemitsu** [comment]
It's a little busted, IDK what's going on

**Comment by 1393F** [comment]
> 
> 
> It's a little busted, IDK what's going on

wdym?

**Comment by JohnFulpWillard** [comment]
another feature being held back by the lack of combat mode

**Comment by EgorDinamit** [comment]
> another feature being held back by the lack of combat mode

I don't see how's the combat mode needed here.

**Comment by JohnFulpWillard** [comment]
> 
> 
> > another feature being held back by the lack of combat mode
> 
> I don't see how's the combat mode needed here.

https://github.com/tgstation/tgstation/pull/59241

**Comment by Kitsunemitsu** [comment]
We'll update to combat mode over my dead body.

**Comment by EgorDinamit** [comment]
> > > another feature being held back by the lack of combat mode
> > 
> > 
> > I don't see how's the combat mode needed here.
> 
> [tgstation/tgstation#59241](https://github.com/tgstation/tgstation/pull/59241)

Yet another fulpstation propaganda. Combat Mode is NOT needed at all.

**Comment by retlaw34** [comment]
that feature could work like this without combat mode:
move left click into move into the firelock with a crowbar in hand to open it temporarily, think monstermos firelocks
move right click into left click with a crowbar to open it permanently

**Pull request closed without merging**
