### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by DaddyIssues98**
i will fight until the end for the dog, i dont even like pugs but i dont like when people remove thing for my map

## About The Pull Request

siempre es bueno tener la mascota.

## Why It's Good For The Game

Esto arregla la mascota perdida que seguridad, No tener la mascota del departamento baja la moral en el trabajo, provoca tendencias suicidas y aumenta el consumo de alimentos de los empleados. 

## Changelog
:cl:
fix: missing pet
/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
negada.
Normalmente tengo tolerancia para esto, pero esta vez no.

**Comment by Kitsunemitsu** [comment]
I get it Annie, but maintainers have to do it anyways. When we add a new feature, someone will have to update the map, and usually that's the person to update the feature.

**Comment by DaddyIssues98** [comment]
it was more of a joke, i put it in draft to get the real fixes xD

**Comment by Kitsunemitsu** [comment]
Oh, I can re-open it for you, if you want.

**Pull request closed without merging**
