### PR TITLE
Respriting part 2: Guns

### PR DESCRIPTION
**Pull request by retlaw34**
## About The Pull Request

Resprites, a lot of guns
Most of these are by @triplezeta, many thanks to them for the sprites and helping me with the ones i did
The m90 is made by shwick
Revolvers(with the exception of the detective special) and the bungalow guns were done by me, thanks for zeta for helping me with them again
ports https://github.com/shiptest-ss13/Shiptest/pull/326/files
image

## Why It's Good For The Game

Gives us a unique identity, and fuck soul

## Changelog
:cl:
imageadd: Respritesa a lot of guns
/:cl:

### CODE REVIEW

**Comment by BootlegBow** [comment]
now nicole can commit mass genocide _in style_

**Review by BootlegBow — APPROVED** [review]

**Comment by retlaw34** [comment]
Havent felt like finishing this

**Comment by Kitsunemitsu** [comment]
Opening and merging. It's not finished, but the new sprites are well-liked. the not done ones will look strange, which is alright, I guess

**Comment by BootlegBow** [comment]
kirie forcefully opens another coders pr

**Comment by Kitsunemitsu** [comment]
I think it's good to go, but netta told me to omit one sprite, I'm awaiting to see which one it is

**Comment by retlaw34** [comment]
@Kitsunemitsu its the p90 or m90

**Comment by retlaw34** [comment]
Actually you know what? it should be fine

**Comment by Kitsunemitsu** [comment]
Ok, so this looks good. I think it's good to merge, the community loves it too.

**Pull request merged**
