### PR TITLE
Computer restyle

### PR DESCRIPTION
**Pull request by retlaw34**
## About The Pull Request

mirror of https://github.com/shiptest-ss13/Shiptest/pull/432

## Why It's Good For The Game

it looks neat

## Changelog
:cl:
imageadd: Almost every single computer sprite has been redone
/:cl:

### CODE REVIEW

**Comment by GoodDays13** [comment]
image
image
why does alert-red seem to lose a bar thing under it but alert-green doesn't?

**Comment by retlaw34** [comment]
thats a mistake on my part

**Comment by retlaw34** [comment]
Actually that might have to do with i put almost minimal effort into the modular computers

**Comment by GoodDays13** [comment]
i don't know anything about how the computers and sprites work, so idk if this is bad, but the height of the sprites is still wacky. some are different than others and i compared them to the computer
image
image

**Comment by retlaw34** [comment]
Yeah some sprites have a slight height issue, i need to fix that

**Comment by retlaw34** [comment]
Unpopular.

**Comment by retlaw34** [comment]
might as well finish this

**Comment by DaddyIssues98** [comment]
i want then, they look good.

**Pull request merged**
