### PR TITLE
Ports updated readme

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

I came here to laugh at PRs, only to see my own shitty PRs' effects.

## Why It's Good For The Game

It isn't, but it is good for my eyes.

## Changelog
Not needed, not touching anything game-related.

### CODE REVIEW

**Comment by Nobelium-XVIII** [comment]
John Fulp Willard, contributor at Bungalow

**Comment by FernandoJ8** [comment]
Speedmerge

**Comment by HugoOdaX** [comment]
:trollface:

**Comment by Kitsunemitsu** [comment]
> I came here to laugh at PRs, only to see my own shitty PRs' effects.

Yeah, sounds about right.
This is just a readme file update, looks pretty good. will probably speedmerge

**Comment by BootlegBow** [comment]
john willard on his way to become a contributor on every ss13 server

**Comment by JohnFulpWillard** [comment]
> 
> 
> john willard on his way to become a contributor on every ss13 server

I was told that PR'ing upstream is best

**Pull request merged**
