### PR TITLE
Minor code improvements

### PR DESCRIPTION
**Pull request by DerpiestBruh**
<If you have constructive feedback, concerns (that havent already been voiced), ideas (i.e. for things that we need before removal), you can voice them below. If you don't, please use the thumb buttons or whatever.

Before you comment, your concern may already have been answered. Be warned this is a wall of text, but take a look at #48668 (comment) and #48668 (comment)
Discussion moved to https://tgstation13.org/phpBB/viewtopic.php?f=10&t=25203
About The Pull Request

This has been in the cards for a while, but consensus is finally that we have enough alternative systems in place to do this. They might still need polish, there might be things we need to do before this is fully merged, so lets get cracking.
This PR entirely removes cloning from the codebase, except for a few bits and bobs required for podcloning. For now that is tentatively left in, but if it becomes the new must do meta, that's gonna need some changing up. Heavy restrictions on availability is a possibility.
Note that locking cloning behind late game tech has been discussed ad nauseum, but I don't think thats the right way forward. If we however decide to go down that road, I would rather see reworked cloning brought back in a limited capacity than the unbalanced abomination we currently have.

The cloning labs on all the maps have been replaced by extensions of the wards that the genetics move PR left behind and some clothes storage, so this brand new open realestate located centrally in medbay is ready for someone to fill in with their exciting new changes.

Replica pod seed availability reduced greatly. No longer available in megaseed vendor, cargo crate down to 1 from 3. No change to mutation or growing new seeds, these are already low yield.

Dead body chem purging, alternatively in stasis chem purging. This is likely not a big issue, as we still have chem purgers like pentetic. Large doses may be hard to deal with though. See
Adds a new surgery, "Stomach Pump" #48728 for one approach.
Look at the viability of late stage defibbing. In particular, time spent, timeframe, available equipment. See
Reduces heart decay, ear damage slightly less bad #48715, happy with the rest
Consider tuning organ decay, in particular heart, eyes and ears. See timeframe above. See
Reduces heart decay, ear damage slightly less bad #48715, happy with the rest
Husking, and how to deal with it efficiently preferrably without brainswap. See Makes husking harder, adds husk healing to instabitaluri #48717,
Makes rezadone cure husking. (alt to #48717) #48726
Fixing a bloodless corpse, preferrably without brainswap. Apply IV drip with blood to corpse, extra blood from cargo or prepwork.
Revival surgery availability early round. Isn't necessary unless heart has been dead for 15+ minutes, aka not roundstart. Edge case surgery, this is fine. 15 minute timer gone in
Reduces heart decay, ear damage slightly less bad #48715
Bio organ vs cybernetic organs and their availability. See Adds basic cybernetic organs, rebalances existing #48714, also

    adds organs to the limbgrower #48679

Closes #48407
Closes #48247
Closes #48173
Closes #46890
Closes #46208
Closes #45653
Closes #44799
Closes #44782
Closes #44614
Closes #41222
Closes #40291
Closes #36347
Closes #36542
Why It's Good For The Game

Cloning is a thorn in medbays side that we need to finally remove. Anything we try to do in medbay has to be balanced against this magical machine that makes everyone better in four button presses (or 0-1 presses if theres part upgrades installed) and a little bit of time. It enables anyone on the station to fully restore a dead person without commiting any significant amount of time or resources to the task, and it is stealing work from our hard(ly) working MD's. Dying should be undesireable, and with cloning available death is quite frankly just too cheap.
Another point well worth mentioning is that doctors quite literally get yelled at by angry patients for not immediately cloning them and instead opting to bring them back (some even fully agumented) through alternate means. Fixing people (and corpses) is supposed to be medbays job, but the ease of moonlighting cloning is making medbay boring and bad.
Changelog

🆑 Skoglol
del: Removes cloning from the codebase. Cloning rooms have been converted to temporary wards and storage. Experimental cloner and its ruin is also gone.
balance: Replica pod seed availability reduced. No longer available in megaseed vendors, seed crate contains one seed down from three. Mutate some cabbages if you want these.
/🆑

### CODE REVIEW

**Comment by SGSDHSD-Enterprise** [comment]
This sucks delete it :|

**Comment by DerpiestBruh** [comment]
> This sucks delete it :|

:/

**Comment by BootlegBow** [comment]
fulp players on their way to troll the bungalow and tegu githubs for no apparent reason

**Comment by Kitsunemitsu** [comment]
Retard moment

**Comment by Sheits** [comment]
> This sucks delete it :|

they did lol

**Pull request closed without merging**
