### PR TITLE
circuits

### PR DESCRIPTION
**Pull request by BootlegBow**
circuits fuck yeah

- [ ] finish the ui
- [ ] fix the bugs
- [ ] compile
- [ ] test

### CODE REVIEW

**Comment by BootlegBow** [comment]
tweak my ass

**Review by retlaw34 — COMMENTED** [review]
I'll be real, I don't think this will ever work without a larger TG merge

**Comment by BootlegBow** [comment]
you're probably right

**Comment by BootlegBow** [comment]
killing, we all know this goes nowhere

**Pull request closed without merging**
