### PR TITLE
Small ships

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request
Adds a pair of small ships for people to fly about in. needs some work though.

## Why It's Good For The Game

idk man

## Changelog
:cl:
add: Added the ships
/:cl:

### CODE REVIEW

**Review by HugoOdaX — COMMENTED** [review]
You should make them a bit damage resistant so they aren't super easy to break

**Comment by BootlegBow** [comment]
wh
gbp
what

**Comment by Kitsunemitsu** [comment]
Great Point, I will fix before merging

**Comment by BootlegBow** [comment]
adding th3 ability to construct and customize these things later on would be great, but for now it looks pretty good

**Comment by Kitsunemitsu** [comment]
I'm actually going to move this into "Mecha" Code to better get the movement type I like

**Comment by Kitsunemitsu** [comment]
Gonna redo another time <3

**Pull request closed without merging**
